package lab9;


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author theme
 */

enum ButtonValues {
    button, button1, button2
}

enum LabelValues {
    label, label1, label2
}

public class MessageJPanel extends javax.swing.JPanel {
    private int key = 13;
    
    /**
     * Creates new form MessageJPanel
     */
    public MessageJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textJTextField = new javax.swing.JTextField();
        okJButton = new javax.swing.JButton();
        textJLabel = new javax.swing.JLabel();

        textJTextField.setText("Введите текст");
        textJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textJTextFieldKeyTyped(evt);
            }
        });

        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        okJButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                okJButtonKeyTyped(evt);
            }
        });

        textJLabel.setText("Текст");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(textJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(textJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(okJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textJLabel)
                    .addComponent(textJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(okJButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okJButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okJButtonKeyTyped
        if (evt.getKeyCode() == key) {
            okJButton.doClick();
        }
    }//GEN-LAST:event_okJButtonKeyTyped

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        JOptionPane.showMessageDialog(okJButton, textJTextField.getText());
    }//GEN-LAST:event_okJButtonActionPerformed

    private void textJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textJTextFieldKeyTyped
        if (evt.getKeyCode() == key) {
            okJButton.doClick();
        }
    }//GEN-LAST:event_textJTextFieldKeyTyped

    ButtonValues buttonValues;

    public ButtonValues getButton() {
        return buttonValues;
    }

    public void setButton(ButtonValues buttonValues) {
        this.buttonValues = buttonValues;
        
        switch (this.buttonValues) {
            case button:
                okJButton.setText("Нажми");
                break;
            case button1:
                okJButton.setText("Ок");
                break;
            case button2:
                okJButton.setText("OK");
                break;
        }
    }
    
    LabelValues labelValues;
    
    public LabelValues getLabel() {
        return labelValues;
    }
    
    public void setLabel(LabelValues labelValues) {
        this.labelValues = labelValues;
        
        switch (this.labelValues) {
            case label:
                textJLabel.setText("Текст");
                break;
            case label1:
                textJLabel.setText("Ваш текст");
                break;
            case label2:
                textJLabel.setText("Text");
                break;
        }
    }
    
    public int getKey() {
        return key;
    }
    
    public void setKey(int key) {
        this.key = key;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okJButton;
    private javax.swing.JLabel textJLabel;
    private javax.swing.JTextField textJTextField;
    // End of variables declaration//GEN-END:variables
}
